### ISSUE TITLE
Datetime type not handled

### ISSUE THREAD

**Issue by pmbohm** [aodn/geoserver-layer-filter-extension#19]
There is a type missmatch where datetime is not recognised as a java class by the filter extension.
Blocking aodn/aodn-portal#1707

## What happens
```
http://geoserver-123.aodn.org.au/geoserver/wms?request=uniqueValues&service=layerFilters&version=1.0.0&workspace=imos&layer=argo_profile_layer_map&propertyName=juld
```
This fails as juld is not recognised as a java date
```
Caused by: java.lang.RuntimeException: Unrecognized type
	at au.org.emii.geoserver.extensions.filters.layer.data.ValuesDocument.encodeValues(ValuesDocument.java:90)
	at au.org.emii.geoserver.extensions.filters.layer.data.ValuesDocument.build(ValuesDocument.java:30)
	at au.org.emii.geoserver.extensions.filters.LayerFiltersService.getUniqueValuesDocument(LayerFiltersService.java:108)
```
## What should happen 
All filterable types should be handled

**Comment by dnahodil** [comment]
Fixed by #21
